include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ThreadedConfig.cmake")

function(mmix_threaded_file root path)
  if(NOT IS_ABSOLUTE "${root}" OR NOT IS_ABSOLUTE "${path}" OR
     NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "MMIX pthread C++ requires an existing absolute input: ${path}")
  endif()
  file(REAL_PATH "${root}" root)
  file(REAL_PATH "${path}" path)
  string(FIND "${path}" "${root}/" inside)
  if(NOT inside EQUAL 0)
    message(FATAL_ERROR "MMIX pthread C++ input escapes its provider root: ${path}")
  endif()
endfunction()

set(libc_build "${LIBCXX_MMIX_LINUX_LIBC_BUILD}")
set(rt_build "${LIBCXX_MMIX_LINUX_COMPILER_RT_BUILD}")
mmix_threaded_file("${libc_build}" "${libc_build}/mmix-threaded-libc/inputs.json")
file(READ "${libc_build}/mmix-threaded-libc/inputs.json" inputs)
option(LIBCXXABI_MMIX_LINUX_TLS_DESTRUCTORS
  "Prepare fail-closed MMIX libc++abi TLS registration" OFF)
if(LIBCXXABI_MMIX_LINUX_TLS_DESTRUCTORS)
  foreach(component unwind_roots tls_destructors)
    string(JSON enabled ERROR_VARIABLE missing GET "${inputs}" ${component})
    if(missing OR NOT enabled STREQUAL "ON")
      message(FATAL_ERROR "MMIX libc++abi TLS registration requires libc ${component}=ON")
    endif()
  endforeach()
  set(MMIX_LINUX_THREADED_TLS_DESTRUCTORS_VALIDATED TRUE)
endif()
foreach(key thread_mode errno_mode archive crt headers sysroot uapi)
  string(JSON libc_${key} GET "${inputs}" ${key})
endforeach()
if(NOT libc_thread_mode STREQUAL "LIBC_THREAD_MODE_PLATFORM" OR
   NOT libc_errno_mode STREQUAL "LIBC_ERRNO_MODE_THREAD_LOCAL")
  message(FATAL_ERROR "MMIX pthread C++ requires PLATFORM and THREAD_LOCAL errno")
endif()
file(REAL_PATH "${libc_sysroot}" supplied_sysroot)
file(REAL_PATH "${CMAKE_SYSROOT}" selected_sysroot)
if(NOT supplied_sysroot STREQUAL selected_sysroot)
  message(FATAL_ERROR "MMIX pthread C++ requires the libc sysroot")
endif()
foreach(language C CXX ASM)
  file(REAL_PATH "${CMAKE_${language}_COMPILER}" compiler)
  file(REAL_PATH "${CMAKE_C_COMPILER}" c_compiler)
  if(NOT compiler STREQUAL c_compiler)
    message(FATAL_ERROR "MMIX pthread C++ requires one compiler for all languages")
  endif()
endforeach()
foreach(provider libc rt)
  mmix_threaded_file("${${provider}_build}" "${${provider}_build}/CMakeCache.txt")
  load_cache("${${provider}_build}" READ_WITH_PREFIX INPUT_
    CMAKE_HOME_DIRECTORY CMAKE_C_COMPILER CMAKE_C_COMPILER_TARGET
    CMAKE_CXX_COMPILER CMAKE_CXX_COMPILER_TARGET
    LIBC_CONF_THREAD_MODE LIBC_CONF_ERRNO_MODE LIBC_MMIX_ENABLE_STATIC_TLS
    LIBC_MMIX_BUILD_THREADED_LIBC LIBC_COMPILE_OPTIONS_DEFAULT)
  file(REAL_PATH "${INPUT_CMAKE_C_COMPILER}" compiler)
  file(REAL_PATH "${INPUT_CMAKE_CXX_COMPILER}" cxx_compiler)
  if(NOT compiler STREQUAL c_compiler OR
     NOT cxx_compiler STREQUAL c_compiler OR
     NOT INPUT_CMAKE_C_COMPILER_TARGET STREQUAL "mmix-unknown-linux" OR
     NOT INPUT_CMAKE_CXX_COMPILER_TARGET STREQUAL "mmix-unknown-linux")
    message(FATAL_ERROR "MMIX pthread C++ requires matching ${provider} compiler")
  endif()
  if(provider STREQUAL "libc")
    set(expected_source "${CMAKE_CURRENT_LIST_DIR}/../../../../runtimes")
    if(NOT INPUT_LIBC_CONF_THREAD_MODE STREQUAL libc_thread_mode OR
       NOT INPUT_LIBC_CONF_ERRNO_MODE STREQUAL libc_errno_mode OR
       NOT INPUT_LIBC_MMIX_ENABLE_STATIC_TLS OR NOT INPUT_LIBC_MMIX_BUILD_THREADED_LIBC OR
       NOT "-ftls-model=local-exec" IN_LIST INPUT_LIBC_COMPILE_OPTIONS_DEFAULT OR
       NOT "-fno-lto" IN_LIST INPUT_LIBC_COMPILE_OPTIONS_DEFAULT)
      message(FATAL_ERROR "MMIX pthread C++ requires native PLATFORM libc providers")
    endif()
  else()
    set(expected_source "${CMAKE_CURRENT_LIST_DIR}/../../../../compiler-rt")
  endif()
  file(REAL_PATH "${expected_source}" expected_source)
  file(REAL_PATH "${INPUT_CMAKE_HOME_DIRECTORY}" source)
  if(NOT source STREQUAL expected_source)
    message(FATAL_ERROR "MMIX pthread C++ requires matching ${provider} source")
  endif()
endforeach()

set(builtins "${rt_build}/lib/mmix-unknown-linux/libclang_rt.builtins.a")
foreach(pair "${libc_build}|${libc_archive}" "${libc_build}|${libc_crt}"
             "${rt_build}|${builtins}")
  string(REPLACE "|" ";" paths "${pair}")
  list(GET paths 0 root)
  list(GET paths 1 path)
  mmix_threaded_file("${root}" "${path}")
  get_filename_component(compiler_bin "${CMAKE_C_COMPILER}" DIRECTORY)
  execute_process(COMMAND "${compiler_bin}/llvm-readobj" --file-headers "${path}"
    RESULT_VARIABLE status OUTPUT_VARIABLE headers ERROR_VARIABLE diagnostics)
  string(REGEX MATCHALL "Format: [^\n]+" formats "${headers}")
  if(NOT status EQUAL 0 OR NOT formats)
    message(FATAL_ERROR "Cannot inspect MMIX pthread input: ${path}: ${diagnostics}")
  endif()
  foreach(format IN LISTS formats)
    if(NOT format STREQUAL "Format: elf64-mmix")
      message(FATAL_ERROR "MMIX pthread C++ requires native MMIX ELF inputs")
    endif()
  endforeach()
endforeach()
foreach(header errno.h pthread.h stdlib.h unistd.h time.h sched.h)
  mmix_threaded_file("${libc_build}" "${libc_headers}/${header}")
endforeach()
mmix_threaded_file("${CMAKE_SYSROOT}" "${CMAKE_SYSROOT}${libc_uapi}/asm/unistd.h")
foreach(language C CXX)
  string(APPEND CMAKE_${language}_FLAGS
    " -nostdlibinc -isystem \"${libc_headers}\" -idirafter=${libc_uapi}")
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/InstalledLibc.cmake")
if(NOT RUNTIMES_USE_LIBC STREQUAL "llvm-libc")
  message(FATAL_ERROR "MMIX pthread C++ requires LLVM libc")
endif()
target_link_libraries(runtimes-libc-static INTERFACE "${libc_archive}")
set(LIBCXX_BUILTINS_LIBRARY "${builtins}")
set(LIBCXXABI_BUILTINS_LIBRARY "${builtins}")

# This records prerequisites, not a qualified profile or an installed marker.
set(record "${inputs}")
string(JSON record SET "${record}" status "\"preparation-only\"")
string(JSON record SET "${record}" cxxabi_tls_registration
  "\"${LIBCXXABI_MMIX_LINUX_TLS_DESTRUCTORS}\"")
string(JSON record SET "${record}" builtins "\"${builtins}\"")
foreach(pair "libc|${libc_archive}" "crt|${libc_crt}" "builtins|${builtins}")
  string(REPLACE "|" ";" fields "${pair}")
  list(GET fields 0 name)
  list(GET fields 1 path)
  file(SHA256 "${path}" hash)
  string(JSON record SET "${record}" ${name}_sha256 "\"${hash}\"")
endforeach()
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/mmix-linux-threaded-cxx")
file(WRITE "${CMAKE_BINARY_DIR}/mmix-linux-threaded-cxx/inputs.json" "${record}\n")
message(STATUS "MMIX pthread C++ preparation: unwind locks, cleanup and additional libc providers remain prerequisites")
set(MMIX_LINUX_THREADED_RUNTIME_VALIDATED TRUE)
