# Audited command-environment interface families over the Linux signal runtime.
set(MMIX_COMMAND_ENVIRONMENT_COMPONENTS
  IOCTL TERMIOS JOB_CONTROL EXEC_SEARCH SIGNAL_SUSPEND POLL PROCESS_TIMING
  FILE_METADATA OPTION_PARSING REGEX FNMATCH ACCOUNT_LOOKUP MOUNT_TABLE
  SYSTEM_ADMINISTRATION TEXT_EXTENSIONS PROCESS_CONTROL)
